track-dependencies: false
title: Qgoda
linguas: [en, de]
exclude: 
  - /node_modules
  - /package.json
  - /webpack.config.js
  - /pacakge-lock.json
  - /TODO
  - /LocaleData
  - /postcss.config.js
  - /COPYING
  - /README.md
exclude-watch:
  - /assets
  - "!/_timestamp.json"
  - "!/_includes"
scm: git
no-scm:
  - /assets
helpers:
  npm: npm start
  browser-sync: yarn server
defaults:
  - files:
      - /*/**
      - '!/en/'
    values:
      translate: 
        - title
        - description
        - image_alt
        - button
        - dateFormat
        - readMore
        - tags
  - files: 
      - /en
      - /_includes/en
    values:
      lingua: en
  - files: 
      - /de
      - /_includes/de
    values:
      lingua: de
  - files: /*/docs/**
    values:
      type: doc
      tour: doc
      view: docs.html
  - files: /*/talks/**
    values:
      type: talk 
      view: talks.html
  - files: /*/talks/dpw-2018/**
    values:
      tour: talk-dpw-2018
  - files: /*/news/**
    values:
      type: post
      navsection: news
      author: Guido Flohr
  - files: [index.md, index.html]
    values:
      type: page
      priority: -999 
taxonomies:
  'doc-section': ~
  name: ~
processors:
  chains:
    markdown:
      modules:
      - TT2
      - Strip
      - Hoedown
    html:
      modules:
      - TT2
      - Strip
      - HTMLCleaner
      - HTMLFilter
po:
  textdomain: net.qgoda.www
  msgid-bugs-address: Guido Flohr <guido.flohr@cantanea.com>
  copyright-holder: cantanea EOOD <http://www.cantanea.com/>
  qgoda:
    - perl 
    - -I/Users/guido/perl/qgoda/lib 
    - /Users/guido/perl/qgoda/bin/qgoda
  mdextra:
    - /_includes/**
  tt2:
    - /_views/**
    - "!/_views/raw"
    - "!/_views/functions/**"
  reload: 1
analyzers:
  - GuidedTour

# This should be overridden in _localconfig.yaml or in a private branch.
legal:
  name: configure legal.name in _localconfig.yaml or _config.yaml
  street: configure legal.street in _localconfig.yaml or _config.yaml
  city: configure legal.city in _localconfig.yaml or _config.yaml
  id: configure legal.id in _localconfig.yaml or _config.yaml
  vat-id: configure legal.vat-id in _localconfig.yaml or _config.yaml
  email: configure legal.email in _localconfig.yaml or _config.yaml
  phone: configure legal.phone in _localconfig.yaml or _config.yaml
  manager: configure legal.manager in _localconfig.yaml or _config.yaml
  responsible: configure legal.responsible in _localconfig.yaml or _config.yaml
  copyright_year: configure legal.copyright_year in _localconfig.yaml or _config.yaml
  copyright_uri: configure legal.copyright_uri in _localconfig.yaml or _config.yaml
  # url: http://www.yourname.org/
google:
  #analytics_id: 'UA-XXXXXXX-X'
