name: Deploy Docs with Qgoda

on:
  push:
    branches:
      - '**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build with Qgoda
        uses: gflohr/qgoda-action@v1
        with:
          qgoda-version: latest-node
          alpine-dependencies: git

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::403172062108:role/GitHubActionsQgodaSite-Role-KrY8I17nCB4b
          aws-region: us-east-1

      - name: Deploy to S3 Bucket
        uses: osiegmar/s3-publisher-action@v1
        with:
          bucket: www.qgoda.net
          dir: ./_site

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E2OTW00HQIINAZ --paths '/*'
        shell: sh
